project:
  type: website
  output-dir: docs

website:
  title: "EricChu666.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - text: projects
        href: projects.qmd
        menu: 
          - text: Big Data (Driver & Truck)
            href: big-data.html

            
      - href: 'Pin-Yu Chu Resume.pdf'
        text: CV

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

